[features]
seeds = false
skip-lint = false
[programs.localnet]
sol_betting_game = "6f2TEQ8Vva4J3dmRnQ5VLYXUUysJb6Gab8yUCjhWK2Ds"
[programs.devnet]
sol_betting_game = "6f2TEQ8Vva4J3dmRnQ5VLYXUUysJb6Gab8yUCjhWK2Ds"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/rustam/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/sol_betting_game.ts"