[features]
seeds = false
skip-lint = false
[programs.mainnet]
sol_betting_game = "CfjtNRosShHzVXAh9EJ72j8DvZqVjda6HnUauQuE9Bb3"
[programs.localnet]
sol_betting_game = "CfjtNRosShHzVXAh9EJ72j8DvZqVjda6HnUauQuE9Bb3"
[programs.devnet]
sol_betting_game = "CfjtNRosShHzVXAh9EJ72j8DvZqVjda6HnUauQuE9Bb3"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "/Users/rustam/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/sol_betting_game.ts"