[features]
seeds = false
skip-lint = false
[programs.devnet]
sol_betting_game = "5xs7Wco75e1tJfuSqb72992SqDZBEVxW1CMhUZg7x9G8"

[programs.localnet]
sol_betting_game = "5xs7Wco75e1tJfuSqb72992SqDZBEVxW1CMhUZg7x9G8"

[programs.mainnet]
sol_betting_game = "5xs7Wco75e1tJfuSqb72992SqDZBEVxW1CMhUZg7x9G8"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Mainnet"
wallet = "/Users/rustam/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/sol_betting_game.ts"
