[features]
seeds = false
skip-lint = false
[programs.localnet]
sol_betting_game = "9VR2nRtwUNVR52HTqfWycxKUG1rfHtDnH16Xfqksyp72"
[programs.devnet]
sol_betting_game = "9VR2nRtwUNVR52HTqfWycxKUG1rfHtDnH16Xfqksyp72"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/rustam/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/sol_betting_game.ts"
deployyy = "yarn run ts-node ./migrations/deploy.ts"
inter = "yarn run ts-node ./migrations/interact.ts"