[features]
seeds = false
skip-lint = false
[programs.localnet]
sol_betting_game = "8FFkzD327EcqEViecB8eJC3JE4zDso3rq4UjeZSTwiNy"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/rustam/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
